name: CI

on:
  push:
    branches: [main, master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  devenv-ci:
    name: devenv ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Install devenv
        run: nix profile install --accept-flake-config github:cachix/devenv/latest
      - name: Update devenv lock
        run: devenv update
      - name: Run devenv ci
        run: devenv ci
  flake-check:
    name: Flake Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix flake check
        run: nix flake check
  build-packages:
    name: Build ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [xpdig, ash]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build ${{ matrix.package }}
        run: nix build .#${{ matrix.package }}
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check formatting
        run: nix fmt -- --fail-on-change
  eval-modules:
    name: Evaluate devenv modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Evaluate flake outputs
        run: nix eval .#devenvModules --apply builtins.attrNames
